online_test/urls.py
from django.urls import path
from online_test import views
app_name='user'
urlpatterns = [
    path("",views.welcome,name='welcome'),
    path("signup",views.signup,name='signup'),
    path("store_user",views.store_user,name='store_user'),
    path("login",views.login,name='login'),
    path("homepage",views.homepage,name='homepage'),
    path("profile",views.profile,name='profile'),
    path("profile_save",views.profile_save,name='profile_save'),
    path("logout",views.logout,name='logout'),
    path("aboutUs",views.aboutUs,name='aboutUs'),
    path("view_profile",views.view_profile,name='view_profile'),
    path("pay",views.pay,name='pay'),
    path("success",views.success,name='success'),

    path('heart', views.heart, name="heart"),
    path('ChatBot', views.ChatBot, name="ChatBot"),

    path('xray', views.index, name='index'),
    path('import_data/', views.import_data, name='import_data'),
    path('train_model/', views.train_model, name='train_model'),
    path('predict_model/', views.predict_model, name='predict_model'),
]

ots/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("online_test.urls")),
]

online_test/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username=models.CharField(primary_key=True,max_length=30)
    password=models.CharField(max_length=10,null=False)
    name=models.CharField(max_length=30,null=False)
    def __str__(self):
        return self.name
    
class Profile(models.Model):
    username=models.ForeignKey(User,on_delete=models.CASCADE,primary_key=True)
    fathers_name=models.CharField(max_length=30,default='')
    mothers_name=models.CharField(max_length=30,default='')
    phone=models.CharField(max_length=10,default='')
    email=models.CharField(max_length=30,default='')
    address=models.CharField(max_length=50,default='')
    def __str__(self):
        return self.fathers_name
    
    
class Test_history(models.Model):
    test_id=models.BigAutoField(auto_created=True,primary_key=True)
    username=models.ForeignKey(User,on_delete=models.CASCADE)
    subject=models.CharField(max_length=25,default='')
    total=models.IntegerField()
    correct=models.IntegerField()
    wrong=models.IntegerField()
    percentage=models.IntegerField()

class Test_paper_subject1(models.Model):
    q_id=models.IntegerField(primary_key=True)
    ques=models.CharField(max_length=100)
    a=models.CharField(max_length=50)
    b=models.CharField(max_length=50)
    c=models.CharField(max_length=50)
    d=models.CharField(max_length=50)
    ans=models.CharField(max_length=2)
    def __str__(self):
        return self.ques
    
class Test_paper_subject2(models.Model):
    q_id=models.IntegerField(primary_key=True)
    ques=models.CharField(max_length=100)
    a=models.CharField(max_length=50)
    b=models.CharField(max_length=50)
    c=models.CharField(max_length=50)
    d=models.CharField(max_length=50)
    ans=models.CharField(max_length=2)
    def __str__(self):
        return self.ques
    
class Test_paper_subject3(models.Model):
    q_id=models.IntegerField(primary_key=True)
    ques=models.CharField(max_length=100)
    a=models.CharField(max_length=50)
    b=models.CharField(max_length=50)
    c=models.CharField(max_length=50)
    d=models.CharField(max_length=50)
    ans=models.CharField(max_length=2)
    def __str__(self):
        return self.ques
    
class Payment(models.Model):
    name = models.CharField(max_length=100)
    amount = models.IntegerField()
    order_id = models.CharField(max_length=100, unique=True)
    paid = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    

online_test/forms.py
from django import forms


class BreastCancerForm(forms.Form):

    radius = forms.FloatField(label='Mean Radius', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    texture = forms.FloatField(label='Mean Texture', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    perimeter = forms.FloatField(label='Mean Perimeter', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    area = forms.FloatField(label='Mean Area', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    smoothness = forms.FloatField(label='Mean Smoothness', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))


class DiabetesForm(forms.Form):

    pregnancies = forms.FloatField(label='Pregnancies', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    glucose = forms.FloatField(label='Glucose', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    bloodpressure = forms.FloatField(label='Blood Pressure', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    skinthickness = forms.FloatField(label='Skin Thickness', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    insulin = forms.FloatField(label='Insulin', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    bmi = forms.FloatField(label='BMI', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    pedigree = forms.FloatField(label='Pedigree', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    age = forms.FloatField(label='Age', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))


class HeartDiseaseForm(forms.Form):

    age = forms.FloatField(label='Age', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    sex = forms.FloatField(label='Sex', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    cp = forms.FloatField(label='CP', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    trestbps = forms.FloatField(label='TRESTBPS', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    chol = forms.FloatField(label='CHOL', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    fbs = forms.FloatField(label='FBS', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    restecg = forms.FloatField(label='RESTECG', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    thalach = forms.FloatField(label='THALACH', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    exang = forms.FloatField(label='EXANG', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    oldpeak = forms.FloatField(label='OLDPEAK', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    slope = forms.FloatField(label='SLOPE', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    ca = forms.FloatField(label='CA', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    thal = forms.FloatField(label='THAL', min_value=0, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}))

online_test/views.py
import os
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse
from online_test.models import *
from django.views.decorators.csrf import csrf_exempt #include this 
import random
import razorpay
from django.http import JsonResponse
import google.generativeai as ai
from django.http import JsonResponse
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

from ots import settings
from .forms import BreastCancerForm, DiabetesForm, HeartDiseaseForm

def welcome(request):
    template=loader.get_template("welcome.html")
    res=template.render()
    return HttpResponse(res)

def signup(request):
    template=loader.get_template("signup.html")
    res=template.render()
    return HttpResponse(res)

@csrf_exempt # include  this
def store_user(request):
    if request.method=='POST':
        username=request.POST['username']
        if(len(User.objects.filter(username=username))):
            msg='username already taken ....try another username'
            context={
                'msg':msg
            }
            template=loader.get_template("signup.html")
            res=template.render(context,request)
            return HttpResponse(res)
        else:
            user=User() # insertion
            user.username=username
            user.password=request.POST['password']
            user.name=request.POST['name']
            user.save()
            template=loader.get_template("login.html")
            res=template.render()
            return HttpResponse(res)
    else:
        msg='invalid request......first signup'
        context={
            'msg':msg
        }
        template=loader.get_template("signup.html")
        res=template.render(context,request)
        return HttpResponse(res)
    
@csrf_exempt # include  this
def login(request): #authentication
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        if(len(User.objects.filter(username=username))):
            user=User.objects.filter(username=username)
            if(len(user.filter(password=password))):
                request.session['username']=username # login success then ...
                user_data=User.objects.filter(username=username)
                profile_data=Profile.objects.filter(username=username)
                context={
                    'user_data':user_data,
                    'profile_data':profile_data
                }
                template=loader.get_template("homepage.html")
                res=template.render(context,request)
                return HttpResponse(res)
            else:
                msg='incorrect password.......login again'
                context={
                    'msg':msg
                }
                template=loader.get_template("login.html")
                res=template.render(context,request)
                return HttpResponse(res)
        else:
            msg='incorrect username........login again'
            context={
                'msg':msg
            }
            template=loader.get_template("login.html")
            res=template.render(context,request)
            return HttpResponse(res)
    else:
        template=loader.get_template("login.html")
        res=template.render()
        return HttpResponse(res)

def homepage(request):
    if 'username' not in request.session.keys(): 
        template=loader.get_template("welcome.html")
        res=template.render()
        return HttpResponse(res)
    else:
        username=request.session['username']
        user_data=User.objects.filter(username=username)
        profile_data=Profile.objects.filter(username=username)
        context={   
            'user_data':user_data,
            'profile_data':profile_data
        }
        template=loader.get_template("homepage.html")
        res=template.render(context,request)
        return HttpResponse(res)

def profile(request):
    template=loader.get_template("profile.html")
    res=template.render()
    return HttpResponse(res)

@csrf_exempt # include  this
def profile_save(request):
    if request.method=='POST':
        username=request.session.get('username')
        if(len(User.objects.filter(username=username))):
            profile=Profile() #insertion
            profile.username=User.objects.get(username=username)
            profile.fathers_name=request.POST['father_name']
            profile.mothers_name=request.POST['mother_name']
            profile.phone=request.POST['phone']
            profile.email=request.POST['email']
            profile.address=request.POST['address']
            profile.save()
            user_data=User.objects.filter(username=username)
            profile_data=Profile.objects.filter(username=username)
            context={
                'user_data':user_data,
                'profile_data':profile_data
            }
            template=loader.get_template("homepage.html")
            res=template.render(context,request)
            return HttpResponse(res)
        else:
            msg='incorrect username ,profile not updated'
            context={
                'msg':msg
            }
            template=loader.get_template("profile.html")
            res=template.render(context,request)
            return HttpResponse(res)
    else:
        template=loader.get_template("welcome.html")
        res=template.render()
        return HttpResponse(res)


def logout(request):
    del request.session['username'] #must destroy session keys
    template=loader.get_template("welcome.html")
    res=template.render()
    return HttpResponse(res)

def aboutUs(request):
    template=loader.get_template("about.html")
    res=template.render()
    return HttpResponse(res)


def view_profile(request):
    if 'username' not in request.session.keys(): 
        template=loader.get_template("welcome.html")
        res=template.render()
        return HttpResponse(res)
    else:
        username=request.session['username']
        user_data=User.objects.filter(username=username)
        profile_data=Profile.objects.filter(username=username)
        context={   
            'user_data':user_data,
            'profile_data':profile_data
        }
        template=loader.get_template("view_profile.html")
        res=template.render(context,request)
        return HttpResponse(res)

@csrf_exempt 
def pay(request):
    if request.method == "POST":
        name = request.POST.get('name')
        amount = int(request.POST.get('amount')) * 100  # Razorpay amount is in paise
        #Create Order 
        client = razorpay.Client(auth=("rzp_live_BlFpg6CStP8yfm", "QVxFEhGvT6cmurWYPHKsgyQj"))
        data = { "amount": amount, "currency": "INR", "receipt": "order_rcptid_11" }
        payment = client.order.create(data=data)
        # saving details in out db
        pay = Payment()
        pay.name=name
        pay.amount=amount/100 
        pay.order_id=payment['id']
        pay.save()
        context={
            'payment': payment,
            'name': name
        }
        template=loader.get_template("payment.html")
        res=template.render(context,request)
        return HttpResponse(res)
    template=loader.get_template("pay.html")
    res=template.render()
    return HttpResponse(res)

@csrf_exempt
def success(request):
    if request.method == "POST":
        order_id = request.POST.get("razorpay_order_id", "")
        user = Payment.objects.get(order_id=order_id)
        # optionally we can store these details in our db
        # print(request.POST.get("razorpay_payment_id", ""))
        # print(request.POST.get("razorpay_order_id", ""))
        # print(request.POST.get("razorpay_signature", ""))
        if user:
            user.paid = True
            user.save()
            return render(request, "success.html")
        else:
            context={
                "message": "Order ID not found in the database."
            }
            template=loader.get_template("error.html")
            res=template.render(context,request)
            return HttpResponse(res)
    context={
        "message": "Invalid request method."
    }
    template=loader.get_template("error.html")
    res=template.render(context,request)
    return HttpResponse(res)


def heart(request):
    """
    Lung Cancer Prediction
    """
    # Update the file path to point to the 'data' directory
    file_path = os.path.join(settings.BASE_DIR, 'data', 'LungCancer_train.csv')

    try:
        df = pd.read_csv(file_path)
    except FileNotFoundError:
        # Handle the case where the file is not found
        return HttpResponse("Error: Dataset file not found. Please check the file path.", status=500)

    data = df.values
    X = data[:, :-1]  # Features
    Y = data[:, -1:]  # Target variable (0: No Cancer, 1: Cancer Detected)

    value = ''

    if request.method == 'POST':
        # Replace with lung cancer-related input features
        age = float(request.POST['age'])
        smoking_history = float(request.POST['smoking_history'])
        alcohol_use = float(request.POST['alcohol_use'])
        coughing_duration = float(request.POST['coughing_duration'])
        breathlessness = float(request.POST['breathlessness'])
        chest_pain = float(request.POST['chest_pain'])
        fatigue = float(request.POST['fatigue'])

        # Create input array
        user_data = np.array(
            (age, smoking_history, alcohol_use, coughing_duration, breathlessness, chest_pain, fatigue)
        ).reshape(1, 7)

        # Train Random Forest model
        rf = RandomForestClassifier(n_estimators=20, criterion='gini', max_depth=10)
        rf.fit(np.nan_to_num(X), Y)
        predictions = rf.predict(user_data)

        if int(predictions[0]) == 1:
            value = 'have lung cancer'
        elif int(predictions[0]) == 0:

online_test/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>error occured</h1>
</body>
</html>

online_test/templates/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Project</title>

  <!-- External Stylesheets and Fonts -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="style.css">
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
  
  <style>
/* General Styles */
body {
      background: radial-gradient(circle, #2c3e50, #000);
      font-family: 'Poppins', sans-serif;
      margin: 0;
      padding: 0;
      color: #ffffff;
      overflow-x: hidden;
    }

    /* Navbar */
    .navbar-brand {
      font-size: 36px;
      font-weight: bold;
      color: #ffffff !important;
      transition: color 0.3s;
    }

    .navbar-brand:hover {
      color: #4caf50;
    }

    .navbar-nav .nav-link {
      font-size: 16px;
      color: #f0f0f0;
      margin-right: 15px;
      transition: color 0.3s, transform 0.3s;
    }

    .navbar-nav .nav-link:hover {
      color: #4caf50;
      transform: scale(1.1);
    }

    .dropdown-menu {
      background-color: #333;
      border: none;
    }

    .dropdown-menu .dropdown-item {
      color: #4caf50;
      font-size: 20px;
      transition: background-color 0.3s, transform 0.3s;
    }

    .dropdown-menu .dropdown-item:hover {
      background-color: #4caf50;
      transform: translateX(5px);
    }

    /* Hero Section */
    #container {
      text-align: center;
      padding: 200px 50px;
      /* background-image: url('static\images\hero.jpg'); Replace with the actual path to your image */
      background-size: cover; /* Ensures the image covers the entire div */
      background-position: center; /* Centers the image */
      background-repeat: no-repeat; /* Prevents the image from repeating */
      border-radius: 15px; /* Optional: Adds rounded corners */
      box-shadow: 0 10px 30px rgba(0, 0, 0, 0.5); /* Optional: Adds a shadow for better visibility */
      color: #ffffff; /* Ensures text remains readable */
    }

    #container h1 {
      font-size: 50px;
      font-weight: bold;
      color: #4caf50;
      margin-bottom: 20px;
      text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.7); /* Optional: Adds text shadow for better visibility */
    }

    #container h2 {
      font-size: 25px;
      font-weight: bold;
      color: #ffffff;
      text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.7); /* Optional: Adds text shadow for better visibility */
    }
    /* Intro Section Styles */
.intro {
  background-color: #f8f9fa; /* Light background for contrast */
  color: #333; /* Default font color */
  padding: 60px 20px; /* Section padding */
}

.intro-feature {
  text-align: center; /* Center-align content */
  margin-bottom: 30px; /* Spacing between features */
}

.intro-icon {
  font-size: 50px; /* Icon size */
  color: #4caf50; /* Icon color */
  margin-bottom: 20px; /* Space below the icon */
}

.intro-content h5 {
  font-size: 22px; /* Font size for headings */
  font-weight: bold; /* Make headings bold */
  color: #4caf50; /* Heading color */
  margin-bottom: 10px; /* Space below the heading */
}

.intro-content p {
  font-size: 16px; /* Font size for paragraphs */
  color: #666; /* Paragraph text color */
  line-height: 1.8; /* Improve readability */
}


    /* Profile Card */
    .card {
      background: linear-gradient(145deg, #1e90ff, #00bfff);
      border: none;
      border-radius: 20px;
      color: #fff;
      padding: 25px;
      margin: 20px auto;
      max-width: 500px;
      box-shadow: 0 10px 30px rgba(0, 0, 0, 0.5);
      transition: transform 0.3s, box-shadow 0.3s;
      position: relative;
      overflow: hidden;
    }

    .card:hover {
      transform: translateY(-10px);
      box-shadow: 0 15px 40px rgba(0, 0, 0, 0.7);
    }

    .card h2 {
      font-size: 22px;
      margin-bottom: 10px;
    }

    /* Additional Information Section */
    .card1 {
      background: rgba(255,255,255,0);
      border: none;
      border-radius: 0;
      padding: 40px;
      color: #ffffff;
      width: 100vw;
      height: 50vh;
      box-shadow: none;
      margin: 0;
      display: flex;
      align-items: center;
      justify-content: center;
    }

    .card1 p {
      font-size: 18px;
      line-height: 1.8;
      color: #ffffff;
      margin: 0 20px;
      text-align: justify;
    }

    /* Footer */
    footer {
      text-align: center;
      padding: 20px;
      background: #000;
      color: #4caf50;
      font-size: 14px;
    }

    /* Decorative Squares */
    .square {
      position: absolute;
      background: rgba(255, 255, 255, 0.08);
      box-shadow: 0 4px 15px rgba(255, 255, 255, 0.2);
      z-index: -1;
      animation: moveSquare 10s linear infinite;
    }

    .square:nth-child(1) {
      top: 20%;
      left: 10%;
      width: 100px;
      height: 100px;
      animation-duration: 15s;
    }

    .square:nth-child(2) {
      top: 40%;
      right: 15%;
      width: 80px;
      height: 80px;
      animation-duration: 12s;
    }

    .square:nth-child(3) {
      bottom: 10%;
      left: 20%;
      width: 120px;
      height: 120px;
      animation-duration: 18s;
    }

    .square:nth-child(4) {
      bottom: 30%;
      right: 25%;
      width: 90px;
      height: 90px;
      animation-duration: 14s;
    }

    .square:nth-child(5) {
      top: 5%;
      right: 5%;
      width: 70px;
      height: 70px;
      animation-duration: 10s;
    }

    .square:nth-child(6) {
      bottom: 15%;
      left: 5%;
      width: 50px;
      height: 50px;
      animation-duration: 8s;
    }

    /* Moving Squares Animation */
    @keyframes moveSquare {
      0% {
        transform: translate(0px, 0px) rotate(0deg);
      }
      50% {
        transform: translate(30px, -30px) rotate(45deg);
      }
      100% {
        transform: translate(0px, 0px) rotate(0deg);
      }
    }

    /*button*/
.btn-support {
  font-family: 'Poppins', sans-serif;
  font-size: 1.2rem;
  font-weight: 600;
  background: linear-gradient(45deg, #4CAF50, #81C784); /* Green shades for health and positivity */
  border: none;
  color: #ffffff;
  padding: 15px 30px;
  border-radius: 8px;
  cursor: pointer;
  outline: none;
  text-transform: uppercase;
  letter-spacing: 1px;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);
  transition: transform 0.3s ease, box-shadow 0.3s ease, background-color 0.3s ease;
  display: inline-block;
  text-decoration: none;
  text-align: center;
}

.btn-support:hover {
  background: linear-gradient(45deg, #81C784, #4CAF50); /* Inverted gradient for hover effect */
  transform: scale(1.1);
  box-shadow: 0 6px 12px rgba(0, 0, 0, 0.4);
}

.btn-support:focus {
  outline: none;
}

@keyframes pulse {
  0% { transform: scale(1); }
  50% { transform: scale(1.05); }
  100% { transform: scale(1); }
}

.btn-support:active {
  animation: pulse 0.5s ease;
}


    

  </style>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
  <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
    rel="stylesheet"
  />
</head>
<body>
  
    <!-- Decorative Squares -->
    <div class="square"></div>
    <div class="square"></div>
    <div class="square"></div>
    <div class="square"></div>
    <div class="square"></div>
    <div class="square"></div>
  
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Lung Cancer Detection System</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:aboutUs' %}">About Us</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:view_profile' %}">View Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:profile' %}">Update Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:heart' %}">Predict With Data</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:index' %}">Predict With X-Ray</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:ChatBot' %}">ChatBot Support</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

  <!-- Content -->
<div id="container" style="background-image: url('{% static "images/hero.jpg" %}');">
  <h1>Detect Early - Act Early</h1>
  <p>Check Your Lungs' Health:</p>
  <a class="btn-support" href="{% url 'user:pay' %}">Click Here To Support Us</a>
</div>
<section class="intro section-padding">
  <div class="container">
      <div class="row">
          <div class="col-md-4 intro-feature">
              <div class="intro-icon">
                  <span data-icon="&#xe033;" class="icon"></span>
              </div>
              <div class="intro-content">
                  <h5>Advanced Image Analysis</h5>
                  <p>Utilize cutting-edge machine learning algorithms to analyze X-ray images, ensuring accurate and early detection of lung cancer.</p>
                  <a class="btn-support" href="{% url 'user:index' %}">Predict</a>
              </div>
          </div>
          <div class="col-md-4 intro-feature">
              <div class="intro-icon">
                  <span data-icon="&#xe030;" class="icon"></span>
              </div>
              <div class="intro-content">
                  <h5>Symptom-Based Predictions</h5>
                  <p>Input your symptoms to receive reliable predictions based on data-driven insights, providing a comprehensive diagnostic approach.</p>
                  <a class="btn-support" href="{% url 'user:heart' %}">Predict</a>
              </div>
          </div>
          <div class="col-md-4 intro-feature">
              <div class="intro-icon">
                  <span data-icon="&#xe046;" class="icon"></span>
              </div>
              <div class="intro-content last">
                  <h5>Interactive Chatbot</h5>
                  <p>Get personalized advice and preventive measures through our intelligent chatbot, ensuring guidance throughout your health journey.</p>
                  <a class="btn-support" href="{% url 'user:ChatBot' %}">Chat</a>
              </div>
          </div>
      </div>
  </div>
</section>
    <div class="card1" style="background-image: url('{% static "images\testimonials-bg.jpg" %}');">
      <main>
        <p>Welcome to the Lung Cancer Detection System, where we aim to provide a seamless and efficient platform for early diagnosis and assistance in lung cancer detection. Our mission is to empower users with reliable and accessible tools for accurate predictions and guidance.</p>
      
        <p>With cutting-edge machine learning algorithms and a user-centric design, our system revolutionizes the way lung cancer is detected and managed. Our platform offers features such as X-ray image analysis, symptom-based predictions, and an interactive chatbot for medication advice and preventive measures, ensuring a comprehensive healthcare experience.</p>
      
        <p>Whether you are a patient, a healthcare provider, or a researcher, our Lung Cancer Detection System is designed to meet your diagnostic and informational needs. We believe in the power of technology to transform lives and are dedicated to contributing to early detection and improved patient outcomes through our innovative platform.</p>
      </main>
      
    </div>
  
    <footer>
      &copy; 2024 Online Testing System. All rights reserved.
    </footer>
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

online_test/templates/store_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>user created successfully!!!!!</h1>
    <a href="{% url 'user:login' %}">click here to login</a>
    <a href="{% url 'user:welcome' %}">click here for homepage</a>
</body>
</html>